mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO816_Vov2.00_angle64_T5C/summaryPlots/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO816_Vov2.00_angle64_T5C/summaryPlots/tot/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO816_Vov2.00_angle64_T5C/summaryPlots/energy/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO816_Vov2.00_angle64_T5C/summaryPlots/timeResolution/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO816_Vov2.00_angle64_T5C/summaryPlots/timeResolution/fit/’: File exists
Traceback (most recent call last):
  File "moduleCharacterizationSummaryPlots.py", line 339, in <module>
    if (bar not in goodBars[vov]): continue
KeyError: 2.0
