mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_2E14_LYSO100056_Vov1.50_angle52_T-40C/summaryPlots/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_2E14_LYSO100056_Vov1.50_angle52_T-40C/summaryPlots/tot/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_2E14_LYSO100056_Vov1.50_angle52_T-40C/summaryPlots/energy/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_2E14_LYSO100056_Vov1.50_angle52_T-40C/summaryPlots/timeResolution/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_2E14_LYSO100056_Vov1.50_angle52_T-40C/summaryPlots/timeResolution/fit/’: File exists
Traceback (most recent call last):
  File "moduleCharacterizationSummaryPlots.py", line 705, in <module>
    g_tot_vs_bar[l, vov, thRef].Sort()
KeyError: ('L', 1.5, 11)
