mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C/summaryPlots/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C/summaryPlots/tot/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C/summaryPlots/energy/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C/summaryPlots/timeResolution/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C/summaryPlots/timeResolution/fit/’: File exists
Error in <TFile::TFile>: file /eos/home-s/spalluot/MTD/TB_CERN_Sep23/Lab5015Analysis/plots//moduleCharacterization_step2_HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C.root does not exist
Traceback (most recent call last):
  File "moduleCharacterizationSummaryPlots.py", line 139, in <module>
    inputFile = ROOT.TFile.Open(inputdir+'/moduleCharacterization_step2_%s.root'%label)
  File "/usr/lib64/python2.7/site-packages/ROOT/pythonization/_tfile.py", line 67, in _TFileOpen
    raise OSError('Failed to open file {}'.format(str(args[0])))
OSError: Failed to open file /eos/home-s/spalluot/MTD/TB_CERN_Sep23/Lab5015Analysis/plots//moduleCharacterization_step2_HPK_nonIrr_LYSO813_Vov0.80_angle64_T5C.root
